P(b)=" ";
P(barra)="/";
P(mayor)="\">";
P(dospuntos)=":";
P(letraa)="a";
P(letras)="s";
P(paren_i)="(";
P(paren_f)=")";
P(llave_i)="{";
P(llave_f)="}";
P(guion)="-";            
P(blancoIP)="IP:";
P(error)="ERROR";
P(mux)="MUX";
P(dirip)="IP";
P(noesperado)="No esp.";
P(procesaget)="Get";
P(procesapost)="Post";
P(procesaset)="Set";
P(procesajson)="Json";
P(modificada)="modif.:";
P(openserver)="Open server:";
P(closeserver)="Close:";
P(version)="Vers:";
P(muxmode)="MUX:";
P(cwmode)="CWMode:";
P(gwipt)="GW IP";
P(gwport)="GW Port";
P(join)="Join";
P(iniciandovalores)="Iniciando modo fabrica ";
P(tdi)="di";
P(tds)="ds";
P(tea)="ea";
P(ID)="ID";
P(gwssid)="conucogw";
P(gwpass)="conucogw";
P(gwipdef)="192.168.4.1";
P(routerssid)="YOURROUTERSSID";
P(routerpass)="YOURROUTERPASS";
P(apssid)="ESP_9CBE86";
P(appass)="conucogw";
P(enviandoid)="Env. ID:";
P(enviandojson)="Env. Est.:";
P(mododebugon)="CONSOLE ON";
P(mododebugoff)="CONSOLE OFF";
P(setcwmode)="Set CWmode:";
P(blancoscwmode)="CW mode:";
P(treset)="Reset";
P(enviajson)="Envia Json";
P(cipstatus)="CIPStatus:";
P(table)="<table>"; P(table_f)="</table>";
P(td)="<td>";  P(td_f)="</td>"; 
P(tdcolor)="<td bgcolor=\"#FFFF00\">";     // amarillo
P(tr)="<tr>";  P(tr_f)="</tr>";   
P(http)="HTTP";
P(rtssidt)="Router SSID";
P(rtpasst)="Router PASS";
P(gwssidt)="GW SSID";
P(gwpasst)="GW PASS";
P(ssid)="SSID";
P(pass)="PASS";
P(sondas)="Sondas";
P(ver)="VER";
P(esp8266)="ESP8266";
P(crlf)="\r\n";   
P(htmlbody)="<html><body><head><title>Conuco Labs</title></head><table>";
P(form)="<form action=\"save\" method=\"GET\">";
P(htmlbodyform_f)="</form></table></body></html>";
P(htmlbodytable)="<html><body><head><title>Conuco Labs</title></head><table>";
P(htmlbodytable_f)="</table></body></html>";
P(button)="<button>";
P(button_f)="</button>";
P(configeeprom)="EEPROM:";
P(resetesp8266)="Reset ESP8266";
P(conucoremoto)="CONUCO WEB";
P(ready)="Ready";
P(header_i)="HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-length: ";
P(headerother_i)="HTTP/1.1 303 See other\r\nLocation: ";
P(header_f)="\r\n\r\n";
P(resp_404)="HTTP/1.1 404 Page not found\r\nContent-Type: text/html\r\nContent-length: 14\r\n\r\nPage not found";
P(ON)="ON";  P(OFF)="OFF";
P(entdig)="Ent. Dig.";
P(saldig)="Sal. Dig.";
P(entana)="Ent. Ana.";
P(sonda)="Sonda";
P(hrefon)="<a href=\"on?";
P(hrefoff)="<a href=\"off?";
P(a_f)="</a>";
P(faviconlink)="<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://arduino.cc/en/favicon.png\" />";
P(celsius)=" &deg;C";
P(gateway)="Gateway";
P(independiente)="I";
P(Modo)="Modo ";
P(br)="<br>";
P(inputtypetext)="<input type=\"text\""; P(inputtypetext_f)=">";
P(inputtypesubmit)="<input type=\"submit\"";
P(name)=" name=\"";    P(name_f)="\"";
P(value)=" value=\"";  P(value_f)="\"";
P(size)=" size=\"";  P(size_f)="\"";
P(maxlength)=" maxlength=\"";  P(maxlength_f)="\"";
P(sondauno)="Sonda 1";
P(sondados)="Sonda 2";
P(sondatres)="Sonda 3";
P(guardar)="Guardar";
P(menuindex)="<tr><td><a href=\"/setup\">Setup</a><td_f><td></td><tr_f>";
P(menusetup)="<tr><td><a href=\"/\">Panel</a><td_f><td><td_f><tr_f>";
P(Peract)="Per. act. seg. ";
P(apssidt)="AP SSID";
P(appasst)="AP PASS";
P(Canal)="AP Ch";
P(Encmode)="AP Encr.";
P(Cwsap)="AP";
P(RT)="RT";
P(router)="Router";
P(gw)="GW";
P(IP)="IP";
P(conectando)="Conectando con";
P(sta)="STA";
